### ISSUE TITLE
Crossmatching failing due to 'Arrays cannot be empty' error

### ISSUE THREAD

**Issue by jblake95** [jblake95/DebrisWatch#11]
Crossmatching routines are failing due to the following error:
"""
Traceback (most recent call last):
  File "doPhotometry.py", line 354, in <module>
    zp_masked_delta_mag, zp_model = zp_model_fitter(zp_model_init, zp_apass_mag, zp_delta_mag)
  File "/home/james/.local/lib/python3.5/site-packages/astropy/modeling/fitting.py", line 751, in __call__
    weights=filtered_weights, **kwargs)
  File "/home/james/.local/lib/python3.5/site-packages/astropy/modeling/fitting.py", line 178, in wrapper
    return func(self, model, x, y, z=z, **kwargs)
  File "/home/james/.local/lib/python3.5/site-packages/astropy/modeling/fitting.py", line 507, in __call__
    rhs[good], rcond)
  File "/home/james/.local/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 2125, in lstsq
    _assertNoEmpty2d(a, b)  # TODO: relax this constraint
  File "/home/james/.local/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 229, in _assertNoEmpty2d
    raise LinAlgError("Arrays cannot be empty")
numpy.linalg.linalg.LinAlgError: Arrays cannot be empty
"""

**Comment by jblake95** [comment]
Solved - some of the fluxes returned by the rectangular aperture photometry were negative - need to check why (stray bad pixel/ vignetting/ off edge?). This resulted in nans when determining instrumental mags. Removing these suspect objects seemed to do the trick.
